<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>LoadSuppPfr</AssemblyTitle>
    <Description>Load Supplement PFR - Supplement Progress/Final Report Loader</Description>
    <Company>NCI</Company>
    <Product>LoadSuppPfr</Product>
    <Copyright>Copyright © NCI 2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Outlook" Version="15.0.4797.1004" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommonUtilties\CommonUtilties.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.Production.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>