<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
<ItemGroup>
    <PackageReference Include="Microsoft.Office.Interop.Outlook" Version="15.0.4797.1004" />
    <PackageReference Include="Office" Version="12.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="config.csv">
   <CopyToOutputDirectory>Always</CopyToOutputDirectory>
 </Content>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommonUtilties\CommonUtilties.csproj" />
  </ItemGroup>
</Project>
