USE [EIM]
GO

	   
	UPDATE [dbo].[adsup_email_master]
	SET body = 
	'<!doctype html><html><head><meta charset="utf-8"><title>Untitled Document</title></head><body><p>The purpose of this e-mail letter is to inform you that the supplemental application that has been submitted to the National Cancer Institute has been accepted for consideration.  However, this change in status is not meant to indicate an intent to fund the supplemental request.  Instead, NCI staff are in the process of performing an additional review and will make a final determination in the near future.  An estimated date of this decision cannot be provided at this time.</p><p>If you have any questions, with the exception for those in response to PA-23-189, please direct them to the NCI Program Director listed on the most recent Notice of Award.  If your supplement is in response to PA-23-189, please contact the programmatic official provided in the announcement.</p><p>Thank you for your time.</p><p>&nbsp;</p></html>'
	WHERE id = 4;

	UPDATE [dbo].[adsup_email_master]
	SET body = 
	'<!doctype html><html><head><meta charset="utf-8"><title>Untitled Document</title></head><body><p><em>The purpose of this e-mail letter is to inform you that a diversity supplement application has been electronically submitted for the parent grant of the referenced supplement application.  You are listed as the Program Director and Grants Management Specialist, respectively.  </em><o></o></p><p><em>The Center to Reduce Cancer Health Disparities (CRCHD) has been informed by OGA that this application has been submitted and they will begin their review shortly.  The status of this application will be changed to “Accept for Consideration” but this does not equate to the funding of this application.  The grantee will be notified of this change.</em></p><p><em>To the Program Director, this e-mail is to only serve as an FYI that a diversity supplement application has been received.  If you do have any questions or concerns on this supplemental application, please contact <a href="mailto:curesupplements@nih.gov">curesupplements@nih.gov</a> at CRCHD. </em></p><p><em>To the Grants Management Specialist for the parent grant, please review the submitted application and address any concerns including eligibility with <a href="mailto:curesupplements@nih.gov">curesupplements@nih.gov</a> at CRCHD.</em></p><p><em>The application is located in eGrants at the grant number referenced in the subject line.  It is recommended that this be done within the next two weeks to avoid CRCHD’s review of an application that should potentially not be considered.&nbsp; </em></p><p><em>No additional action is required at this time.  As has been done in the past, CRCHD will make the ultimate funding decision on this application.  Any application selected for funding will be done so through the Program Funding Request (PFR) process.  CRCHD will inform OGA of any application that will not be funded, and this will be communicated to the grantee (you will be included on this message).<br></em><br><em>The following link is provided for your reference to the FOAs for the electronic process and the diversity supplement, respectively: <a href="https://grants.nih.gov/grants/guide/pa-files/PA-23-189.html" target="_blank">https://grants.nih.gov/grants/guide/pa-files/PA-23-189.html</a></em><em><p><em>Thank you for your cooperation in this matter.</em></p></html>'
	WHERE id = 16;


GO
