<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>LoadPfr</AssemblyTitle>
    <Description>Load PFR - Progress/Final Report Loader</Description>
    <Company>NCI</Company>
    <Product>LoadPfr</Product>
    <Copyright>Copyright © NCI 2024</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CommonUtilties\CommonUtilties.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="config.csv">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
</Project>