<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <RootNamespace>pdf_file_conversion</RootNamespace>
    <AssemblyName>pdf_file_conversion</AssemblyName>
	<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <!-- Example NuGet dependency -->
    <PackageReference Include="IronPdf" Version="2024.9.3" />
    <PackageReference Include="Markdig" Version="0.44.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="10.0.0" />
    <PackageReference Include="MsgReader" Version="5.6.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="NPOI" Version="2.7.5" />
    <PackageReference Include="Serilog" Version="4.2.0" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="Spire.Doc" Version="12.1.5" />
  </ItemGroup>

</Project>