SET ANSI_NULLS ON
SET QUOTED_IDENTIFIER ON
CREATE TABLE [dbo].[EmailFieldDatatypes](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Type] [varchar](30) COLLATE SQL_Latin1_General_Pref_CP1_CI_AS NOT NULL
) ON [PRIMARY]

GO

