<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <AssemblyTitle>StartOutlook</AssemblyTitle>
    <Company>National Cancer Institute</Company>
    <Product>StartOutlook</Product>
    <Copyright>Copyright © National Cancer Institute 2025</Copyright>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
  </PropertyGroup>
</Project>