"use client";

import { useEffect, useState, useRef } from "react";
import { useAuth } from "@/hooks/useAuth";
import AppShell from "@/components/layout/AppShell";
import SearchForm from "@/components/common/SearchForm";
import { getDashboard } from "@/lib/api";
import type { DashboardResponse } from "@/lib/types";

/* ── Widget configuration ────────────────────────────────────────── */

interface WidgetColumn {
  header: string;
  field: string;
  /** Render cell value as a clickable link to the grant search page */
  isGrantLink?: boolean;
  /** Render cell value as a downloadable file link */
  isFileLink?: boolean;
}

interface WidgetConfig {
  key: string;
  label: string;
  matchTitle: string;
  columns: WidgetColumn[];
  help?: string;
  note?: string;
}

/* Widget definitions keyed for lookup */
const WIDGET_MAP: Record<string, WidgetConfig> = {
  audit_report: {
    key: "audit_report",
    label: "Audit Report",
    matchTitle: "Audit Report",
    columns: [
      { header: "File Name", field: "file_name", isFileLink: true },
      { header: "Run Date", field: "run_date" },
    ],
    help: "Audit report files generated by the system for compliance review.",
  },
  expedited_grants: {
    key: "expedited_grants",
    label: "Expedited Grants",
    matchTitle: "Expedited Grants",
    columns: [
      { header: "Grant", field: "grant", isGrantLink: true },
      { header: "NCAB Date", field: "ncab_date" },
    ],
    help: "Grants flagged for expedited processing.",
  },
  high_priority_competing: {
    key: "high_priority_competing",
    label: "High Priority Competing Grants",
    matchTitle: "High Priority Competing Grants",
    columns: [
      { header: "Grants", field: "grant", isGrantLink: true },
      { header: "Assigned Date", field: "assigned_date" },
    ],
    help: "These grants are nearing OGA deadline for processing, i.e. 60 days for Competing.",
    note: "Note: These grants are nearing OGA deadline for processing, i.e. 60 days for Competing.",
  },
  high_priority_noncompeting: {
    key: "high_priority_noncompeting",
    label: "High Priority Non-Competing Grants",
    matchTitle: "High Priority Non-Competing Grants",
    columns: [
      { header: "Grants", field: "grant", isGrantLink: true },
      { header: "Assigned Date", field: "assigned_date" },
    ],
    help: "These grants are nearing OGA deadline for processing, i.e. 45 days for Non-Competing.",
    note: "Note: These grants are nearing OGA deadline for processing, i.e. 45 days for Non-Competing.",
  },
  late_grants: {
    key: "late_grants",
    label: "Late Grants",
    matchTitle: "Late Grants",
    columns: [
      { header: "Grant", field: "grant", isGrantLink: true },
      { header: "Status", field: "status" },
      { header: "Days Late", field: "days_late" },
    ],
    help: "Grants that have exceeded their processing deadline.",
  },
  link_list: {
    key: "link_list",
    label: "Link List",
    matchTitle: "",
    columns: [],
    help: "Quick-access links configured by your administrator.",
  },
  new_grants: {
    key: "new_grants",
    label: "New Grants - 10 Days",
    matchTitle: "New Grants - 10 Days",
    columns: [
      { header: "Grants", field: "grant", isGrantLink: true },
      { header: "Assigned Date", field: "assigned_date" },
    ],
    help: "These grants have been assigned to you in the last 10 days.",
    note: "Note: These grants have been assigned to you in the last 10 days.",
  },
};

/* Settings sidebar order — alphabetical, matching old system */
const SETTINGS_ORDER = [
  "audit_report",
  "expedited_grants",
  "high_priority_competing",
  "high_priority_noncompeting",
  "late_grants",
  "link_list",
  "new_grants",
];

/* Content pane display order — matches old system grid layout */
const DISPLAY_ORDER = [
  "expedited_grants",           // row 1
  "late_grants",
  "new_grants",
  "high_priority_competing",    // row 2
  "high_priority_noncompeting",
  "link_list",
  "audit_report",               // row 3
];

const WIDGET_OPTIONS = SETTINGS_ORDER.map((k) => ({ key: k, label: WIDGET_MAP[k].label }));

/* ── Loading spinner component ───────────────────────────────────── */

function WidgetSpinner() {
  return (
    <div className="flex items-center justify-center py-6">
      <svg className="animate-spin h-5 w-5 text-primary" viewBox="0 0 24 24" fill="none">
        <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="3" />
        <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
      </svg>
      <span className="ml-2 text-xs text-text-muted">Loading...</span>
    </div>
  );
}

/* ── Help dialog component ───────────────────────────────────────── */

function HelpButton({ title, text }: { title: string; text: string }) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!open) return;
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, [open]);

  return (
    <div ref={ref} className="relative">
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="flex items-center justify-center w-5 h-5 rounded-full bg-primary/10 text-primary text-[11px] font-bold leading-none hover:bg-primary/20 transition-colors"
        title="Help"
      >
        ?
      </button>
      {open && (
        <div className="absolute right-0 top-7 z-50 w-64 rounded-lg border border-border bg-white p-4 shadow-lg fade-in">
          <div className="flex items-start justify-between gap-2 mb-2">
            <h4 className="text-[13px] font-semibold text-text-primary leading-tight">{title}</h4>
            <button
              type="button"
              onClick={() => setOpen(false)}
              className="shrink-0 rounded-full p-0.5 text-text-muted hover:text-text-primary hover:bg-surface-alt transition-colors"
            >
              <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                <line x1="18" y1="6" x2="6" y2="18" />
                <line x1="6" y1="6" x2="18" y2="18" />
              </svg>
            </button>
          </div>
          <p className="text-[12px] text-text-secondary leading-relaxed m-0">{text}</p>
        </div>
      )}
    </div>
  );
}

/* ── Helpers ──────────────────────────────────────────────────────── */

function loadSavedWidgets(): Record<string, boolean> {
  try {
    const saved = localStorage.getItem("dashboardWidgets");
    if (saved) return JSON.parse(saved);
  } catch {}
  return {};
}

/** Best-effort field lookup: exact -> case-insensitive -> stripped underscores -> positional */
function getCellValue(row: Record<string, unknown>, field: string, colIndex?: number): string {
  if (field in row) return String(row[field] ?? "");
  const lower = field.toLowerCase();
  for (const [k, v] of Object.entries(row)) {
    if (k.toLowerCase() === lower) return String(v ?? "");
  }
  const stripped = lower.replace(/_/g, "");
  for (const [k, v] of Object.entries(row)) {
    if (k.toLowerCase().replace(/_/g, "") === stripped) return String(v ?? "");
  }
  if (colIndex !== undefined) {
    const vals = Object.values(row);
    if (colIndex < vals.length) return String(vals[colIndex] ?? "");
  }
  return "";
}

/** Try to find a URL field in the row for file download links */
function getFileUrl(row: Record<string, unknown>): string {
  for (const key of ["file_url", "url", "file_path", "link", "download_url"]) {
    for (const [k, v] of Object.entries(row)) {
      if (k.toLowerCase().replace(/_/g, "") === key.replace(/_/g, "") && v) {
        return String(v);
      }
    }
  }
  return "";
}

/* ── Page component ──────────────────────────────────────────────── */

export default function DashboardPage() {
  const { user, loading } = useAuth();
  const [settingsOpen, setSettingsOpen] = useState(false);
  const [widgetSelections, setWidgetSelections] = useState<Record<string, boolean>>(loadSavedWidgets);
  const [dashboard, setDashboard] = useState<DashboardResponse | null>(null);
  const [dashboardLoading, setDashboardLoading] = useState(false);

  useEffect(() => {
    if (user) {
      setDashboardLoading(true);
      getDashboard()
        .then(setDashboard)
        .catch(console.error)
        .finally(() => setDashboardLoading(false));
    }
  }, [user]);

  if (loading || !user) return null;

  function handleToggleWidget(key: string) {
    setWidgetSelections((prev) => ({ ...prev, [key]: !prev[key] }));
  }

  function handleSave() {
    localStorage.setItem("dashboardWidgets", JSON.stringify(widgetSelections));
    setSettingsOpen(false);
  }

  const activeWidgetKeys = Object.entries(widgetSelections)
    .filter(([, v]) => v)
    .map(([k]) => k);

  return (
    <AppShell user={user}>
      <div className="flex gap-6">
        {/* Settings sidebar — inline, no overlay */}
        {settingsOpen && (
          <div className="w-[220px] shrink-0 fade-in">
            <div className="rounded-xl border border-border bg-white shadow-sm overflow-hidden">
              <div className="flex items-center justify-between px-4 py-3 bg-[#f9fafb] border-b border-border">
                <h3 className="text-[13px] font-semibold text-text-primary">Select Widgets</h3>
                <button
                  onClick={() => setSettingsOpen(false)}
                  className="rounded-full p-0.5 text-text-muted transition-colors hover:bg-surface-alt hover:text-text-primary"
                >
                  <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                    <line x1="18" y1="6" x2="6" y2="18" />
                    <line x1="6" y1="6" x2="18" y2="18" />
                  </svg>
                </button>
              </div>

              <div className="p-3 space-y-0.5">
                <div className="flex items-center justify-between px-2.5 pb-2 mb-1 border-b border-border-light">
                  <button
                    type="button"
                    onClick={() => setWidgetSelections(Object.fromEntries(WIDGET_OPTIONS.map((o) => [o.key, true])))}
                    className="flex items-center gap-1 text-[11px] font-medium text-emerald-600 hover:text-emerald-700 hover:underline"
                  >
                    <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                      <polyline points="20 6 9 17 4 12" />
                    </svg>
                    Select All
                  </button>
                  <button
                    type="button"
                    onClick={() => setWidgetSelections({})}
                    className="flex items-center gap-1 text-[11px] font-medium text-rose-400 hover:text-rose-500 hover:underline"
                  >
                    <svg width="11" height="11" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                      <line x1="18" y1="6" x2="6" y2="18" />
                      <line x1="6" y1="6" x2="18" y2="18" />
                    </svg>
                    Unselect All
                  </button>
                </div>
                {WIDGET_OPTIONS.map((opt) => (
                  <label
                    key={opt.key}
                    className="flex items-center gap-2.5 rounded-md px-2.5 py-2 cursor-pointer text-[13px] text-text-secondary transition-colors hover:bg-surface-alt hover:text-text-primary"
                  >
                    <input
                      type="checkbox"
                      checked={!!widgetSelections[opt.key]}
                      onChange={() => handleToggleWidget(opt.key)}
                      className="rounded border-border accent-primary"
                    />
                    {opt.label}
                  </label>
                ))}
              </div>

              <div className="px-3 pb-3">
                <button
                  onClick={handleSave}
                  className="btn-primary w-full text-[13px]"
                >
                  Save
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Main content — always visible */}
        <div className="flex-1 min-w-0">
          <button
            onClick={() => setSettingsOpen(!settingsOpen)}
            className="status-badge mb-3 bg-primary/10 text-primary cursor-pointer hover:bg-primary/20 transition-colors gap-1"
          >
            <svg width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <circle cx="12" cy="12" r="3" />
              <path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83-2.83l.06-.06A1.65 1.65 0 0 0 4.68 15a1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 2.83-2.83l.06.06A1.65 1.65 0 0 0 9 4.68a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 2.83l-.06.06A1.65 1.65 0 0 0 19.4 9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z" />
            </svg>
            Setting
          </button>

          <SearchForm user={user} />

          {/* Widgets — show shells immediately, spinner while loading */}
          {activeWidgetKeys.length > 0 && (
            <div className="mt-5 grid gap-4 md:grid-cols-3 stagger-children">
              {DISPLAY_ORDER
                .filter((key) => activeWidgetKeys.includes(key))
                .map((key) => {
                  const cfg = WIDGET_MAP[key];

                  // Link List
                  if (key === "link_list") {
                    return (
                      <div key={key} className="dashboard-widget">
                        <div className="dashboard-widget-header flex items-center justify-between">
                          <span>{cfg.label}</span>
                          {cfg.help && <HelpButton title={cfg.label} text={cfg.help} />}
                        </div>
                        <div className="dashboard-widget-body">
                          {dashboardLoading ? (
                            <WidgetSpinner />
                          ) : !dashboard?.links || dashboard.links.length === 0 ? (
                            <p className="text-text-muted text-sm">No data</p>
                          ) : (
                            <ul className="m-0 list-none p-0">
                              {dashboard.links.map((link, i) => (
                                <li key={i} className="mb-1">
                                  <a
                                    href={String(link.Link_url || "#")}
                                    className="text-primary text-sm font-medium hover:text-primary-dark hover:underline transition-colors"
                                    target="_blank"
                                    rel="noopener noreferrer"
                                  >
                                    {String(link.Link_title || "")}
                                  </a>
                                </li>
                              ))}
                            </ul>
                          )}
                        </div>
                      </div>
                    );
                  }

                  // Data widgets
                  const widget = dashboard?.widgets.find(
                    (w) => w.widget_title.toLowerCase() === cfg.matchTitle.toLowerCase(),
                  );

                  return (
                    <div key={key} className="dashboard-widget">
                      <div className="dashboard-widget-header flex items-center justify-between">
                        <span>{cfg.label}</span>
                        {cfg.help && <HelpButton title={cfg.label} text={cfg.help} />}
                      </div>
                      <div className="dashboard-widget-body">
                        {cfg.note && (
                          <p className="text-[11px] italic text-amber-700 bg-amber-50 rounded-md px-2.5 py-1.5 mb-2 leading-relaxed">
                            {cfg.note}
                          </p>
                        )}
                        {dashboardLoading ? (
                          <WidgetSpinner />
                        ) : !widget || widget.data.length === 0 ? (
                          <p className="text-text-muted text-sm">No data</p>
                        ) : (
                          <table className="w-full text-sm table-fixed">
                            <thead>
                              <tr>
                                {cfg.columns.map((col, colIdx) => {
                                  const isLast = colIdx === cfg.columns.length - 1;
                                  return (
                                    <th
                                      key={col.field}
                                      className="px-2 py-1.5 text-left text-[11px] font-semibold uppercase tracking-wider text-text-secondary border-b border-border"
                                      style={isLast && cfg.columns.length > 1 ? { width: "110px" } : undefined}
                                    >
                                      {col.header}
                                    </th>
                                  );
                                })}
                              </tr>
                            </thead>
                            <tbody>
                              {widget.data.slice(0, 10).map((row, i) => (
                                <tr key={i} className={i % 2 === 0 ? "bg-surface-alt" : ""}>
                                  {cfg.columns.map((col, colIdx) => {
                                    const val = getCellValue(row, col.field, colIdx);
                                    const isFirstCol = colIdx === 0 && cfg.columns.length > 1;
                                    return (
                                      <td
                                        key={col.field}
                                        className={`px-2 py-1.5 border-b border-border-light ${isFirstCol ? "overflow-hidden text-ellipsis whitespace-nowrap" : "whitespace-nowrap"}`}
                                      >
                                        {col.isGrantLink && val ? (
                                          <a
                                            href={`/search?q=${encodeURIComponent(val)}`}
                                            className="text-primary font-medium hover:text-primary-dark hover:underline transition-colors"
                                          >
                                            {val}
                                          </a>
                                        ) : col.isFileLink && val ? (
                                          <a
                                            href={getFileUrl(row) || `/content/${val}`}
                                            className="text-primary font-medium hover:text-primary-dark hover:underline transition-colors"
                                            target="_blank"
                                            rel="noopener noreferrer"
                                            title={val}
                                          >
                                            {val}
                                          </a>
                                        ) : (
                                          val
                                        )}
                                      </td>
                                    );
                                  })}
                                </tr>
                              ))}
                            </tbody>
                          </table>
                        )}
                      </div>
                    </div>
                  );
                })}
            </div>
          )}
        </div>
      </div>
    </AppShell>
  );
}
